### PR TITLE
Exercise Raspberry Pi Installation Procedure and Update

### PR DESCRIPTION
**Pull request by phreed**
I exercised the Raspberry Pi installation procedure.
There were issues mostly due to issues in the zero-touch installer related to RaspPi.
Generally, the Raspberry Pi installation procedure has been validated.

I am looking at the zero-touch installer to correct the RaspPi issues.
This PR adds troubleshooting instructions generally for each of the services.
Those troubleshooting pages still need work, which I am working on.

### CODE REVIEW

**Comment by brothercorvo** [comment]
@phreed as far I know we currently need to use old the version of the video server. in this sense should we refer to it with the new name?

**Comment by phreed** [comment]
> @phreed as far I know we currently need to use old the version of the video server. in this sense should we refer to it with the new name?

When we were going through the instructions there was some confusion about ` rtsp-simple-server` vs. `mediamtx`. 
[I](https://github.com/bluenviron/mediamtx). I think referring to the product by its current name (making it clear we are using files with the former name) will result in less confusion but if you prefer the old name I will not be offended.

**Review by brothercorvo — APPROVED** [review]
Ventilated Prose seems a good idea but keep in mind that we have many english as second language contributors

**Review by brothercorvo — APPROVED** [review]

**Comment by brothercorvo** [comment]
Merged

**Pull request merged**
